export const styles = {
  page: { minHeight: '100vh', background: '#141414', color: '#fff', fontFamily: "'Helvetica Neue', Arial, sans-serif", display: 'flex', flexDirection: 'column' },
  nav: { position: 'sticky', top: 0, zIndex: 20, display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '14px 40px', background: '#141414', borderBottom: '1px solid #232323', flexWrap: 'wrap', gap: 10 },
  logo: { color: '#E50914', fontWeight: 900, fontSize: 26, letterSpacing: 1 },
  genreTabs: { gap: 4, flexWrap: 'wrap' },
  genreTab: { background: 'none', border: 'none', color: '#b3b3b3', fontSize: 14, fontWeight: 600, padding: '6px 12px', borderRadius: 4, cursor: 'pointer' },
  genreTabActive: { background: '#333', border: 'none', color: '#fff', fontSize: 14, fontWeight: 700, padding: '6px 12px', borderRadius: 4, cursor: 'pointer' },
  genreTabMobile: { background: 'none', border: 'none', color: '#b3b3b3', fontSize: 15, fontWeight: 600, padding: '10px 4px', textAlign: 'left', cursor: 'pointer', borderBottom: '1px solid #232323' },
  genreTabActiveMobile: { background: 'none', border: 'none', color: '#fff', fontSize: 15, fontWeight: 800, padding: '10px 4px', textAlign: 'left', cursor: 'pointer', borderBottom: '1px solid #E50914' },
  greeting: { color: '#e5e5e5', fontSize: 14 },
  navLoginBtn: { background: '#E50914', color: '#fff', border: 'none', borderRadius: 4, padding: '8px 18px', fontWeight: 700, fontSize: 14, cursor: 'pointer' },
  hamburgerBtn: { background: 'none', border: 'none', color: '#fff', cursor: 'pointer', alignItems: 'center' },
  mobileMenuPanel: { flexDirection: 'column', gap: 4, padding: '10px 40px 18px', background: '#141414', borderBottom: '1px solid #232323' },
  hero: { position: 'relative', minHeight: '78vh', display: 'flex', alignItems: 'center', overflow: 'hidden' },
  spineGrid: { position: 'absolute', inset: 0, display: 'grid', gridTemplateColumns: 'repeat(18, 1fr)', gap: 3, padding: 6, opacity: 0.55 },
  spine: { borderRadius: 2, minHeight: 130, display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: 'inset -2px 0 4px rgba(0,0,0,0.5), inset 2px 0 2px rgba(255,255,255,0.08)' },
  spineText: { writingMode: 'vertical-rl', fontSize: 10, fontFamily: 'Georgia, serif', color: 'rgba(255,255,255,0.75)', whiteSpace: 'nowrap', letterSpacing: 0.5 },
  heroOverlay: { position: 'absolute', inset: 0, background: 'linear-gradient(180deg, rgba(20,20,20,0.65) 0%, rgba(20,20,20,0.9) 60%, #141414 100%)' },
  heroContent: { position: 'relative', zIndex: 1, maxWidth: 720, margin: '0 auto', textAlign: 'center', padding: '0 20px' },
  heroTitle: { fontSize: 48, fontWeight: 900, lineHeight: 1.1, margin: '0 0 16px' },
  heroSub: { fontSize: 19, color: '#e5e5e5', marginBottom: 18 },
  heroCta: { fontSize: 16, marginBottom: 14 },
  heroForm: { display: 'flex', justifyContent: 'center', gap: 8, flexWrap: 'wrap' },
  heroInput: { padding: '14px 16px', fontSize: 16, borderRadius: 4, border: '1px solid #808080', background: 'rgba(0,0,0,0.6)', color: '#fff', minWidth: 280 },
  heroButton: { background: '#E50914', color: '#fff', border: 'none', borderRadius: 4, padding: '14px 24px', fontSize: 17, fontWeight: 700, cursor: 'pointer' },
  authSection: { display: 'flex', justifyContent: 'center', padding: '30px 20px 60px' },
  authCard: { background: 'rgba(0,0,0,0.75)', border: '1px solid #333', borderRadius: 8, padding: '36px 40px', width: '100%', maxWidth: 420 },
  tabRow: { display: 'flex', marginBottom: 24, borderBottom: '1px solid #333' },
  tab: { flex: 1, background: 'none', border: 'none', color: '#808080', fontWeight: 700, fontSize: 15, padding: '10px 0', cursor: 'pointer', borderBottom: '2px solid transparent' },
  tabActive: { flex: 1, background: 'none', border: 'none', color: '#fff', fontWeight: 700, fontSize: 15, padding: '10px 0', cursor: 'pointer', borderBottom: '2px solid #E50914' },
  form: { display: 'flex', flexDirection: 'column', gap: 14 },
  formTitle: { fontSize: 24, fontWeight: 800, margin: '0 0 6px' },
  inputWrap: { display: 'flex', alignItems: 'center', gap: 10, background: 'rgba(255,255,255,0.06)', border: '1px solid #4d4d4d', borderRadius: 4, padding: '12px 14px' },
  input: { flex: 1, background: 'transparent', border: 'none', outline: 'none', color: '#fff', fontSize: 15 },
  eyeBtn: { background: 'none', border: 'none', cursor: 'pointer', display: 'flex', padding: 0 },
  error: { color: '#f66', fontSize: 13, margin: 0 },
  submitBtn: { background: '#E50914', color: '#fff', border: 'none', borderRadius: 4, padding: '14px 0', fontSize: 16, fontWeight: 700, cursor: 'pointer', marginTop: 6 },
  switchText: { color: '#808080', fontSize: 14, textAlign: 'center', marginTop: 4 },
  switchLink: { color: '#fff', fontWeight: 700, cursor: 'pointer' },
  footer: { textAlign: 'center', color: '#666', fontSize: 12.5, padding: '20px 30px 30px' },
  catalogBody: { padding: '20px 40px 40px', flex: 1 },
  row: { marginBottom: 34 },
  rowTitle: { fontSize: 19, fontWeight: 700, margin: '0 0 12px' },
  rowScroll: { display: 'flex', gap: 14, overflowX: 'auto', overflowY: 'hidden', paddingBottom: 8 },
  loadingText: { color: '#808080', fontSize: 14 },
  tileWrap: { position: 'relative', flex: '0 0 auto', display: 'flex', alignItems: 'flex-end' },
  rankNumber: { fontSize: 68, fontWeight: 900, color: '#141414', WebkitTextStroke: '2px #4d4d4d', lineHeight: 1, marginRight: -14, marginBottom: -4, zIndex: 0 },
  tileCover: { width: 128, height: 182, borderRadius: 4, padding: 10, display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', position: 'relative', boxShadow: '0 4px 10px rgba(0,0,0,0.6)', transition: 'transform 0.2s ease', cursor: 'pointer', overflow: 'hidden' },
  coverImg: { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' },
  tileGenre: { position: 'absolute', top: 8, left: 10, fontSize: 9, textTransform: 'uppercase', letterSpacing: 0.5, color: 'rgba(255,255,255,0.6)', fontWeight: 700 },
  tileTitle: { fontSize: 13, fontWeight: 800, lineHeight: 1.15, marginBottom: 3 },
  tileAuthor: { fontSize: 10.5, color: 'rgba(255,255,255,0.65)' },
  tileTitleOverlay: { display: 'block', fontSize: 12.5, fontWeight: 800, marginBottom: 2 },
  tileAuthorOverlay: { display: 'block', fontSize: 10.5, color: 'rgba(255,255,255,0.6)', marginBottom: 6 },
  tileOverlay: { position: 'absolute', inset: 0, background: 'rgba(10,10,10,0.94)', padding: 10, display: 'flex', flexDirection: 'column', justifyContent: 'space-between' },
  tileSynopsis: { fontSize: 10.5, lineHeight: 1.35, color: '#e5e5e5', margin: 0, maxHeight: 80, overflowY: 'auto' },
  tileDownloadBtn: { background: '#E50914', color: '#fff', border: 'none', borderRadius: 4, padding: '7px 0', fontSize: 11.5, fontWeight: 700, cursor: 'pointer' },
};
